from __future__ import annotations

import csv
import io
import json
import statistics
from dataclasses import dataclass, field
from typing import Any

import os

from chad.core.messages import ImageAttachment, ImageFormat
from chad.multimodal.evaluator import ScreenshotDiagramEvaluator
from chad.multimodal.image import ImageConverter
from chad.rag.chunker import TextChunker
from chad.rag.document import DocumentExtractor, FileDocument


@dataclass(frozen=True, slots=True)
class EvidenceLink:
    """Represents a citation or link to specific source evidence in an analysis report."""

    id: str
    source_type: str  # "document", "dataset", "image", "chunk"
    source_id: str
    location: str  # e.g., "row 5", "lines 10-25", "chunk 2", "image properties"
    snippet: str
    confidence: float = 1.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "source_type": self.source_type,
            "source_id": self.source_id,
            "location": self.location,
            "snippet": self.snippet,
            "confidence": self.confidence,
        }


@dataclass(frozen=True, slots=True)
class UncertaintyReport:
    """Explicit report on data quality, ambiguity, sample size, or analysis uncertainties."""

    overall_uncertainty: float  # 0.0 (certain) to 1.0 (highly uncertain)
    reasons: tuple[str, ...]
    missing_data_count: int = 0
    sample_size_warning: bool = False
    ambiguous_sources: tuple[str, ...] = field(default_factory=tuple)

    def to_dict(self) -> dict[str, Any]:
        return {
            "overall_uncertainty": round(self.overall_uncertainty, 3),
            "reasons": list(self.reasons),
            "missing_data_count": self.missing_data_count,
            "sample_size_warning": self.sample_size_warning,
            "ambiguous_sources": list(self.ambiguous_sources),
        }


@dataclass(frozen=True, slots=True)
class DatasetSummary:
    """Statistical summary of a structured dataset (CSV, JSON table, list of dicts)."""

    row_count: int
    column_count: int
    column_names: tuple[str, ...]
    column_types: dict[str, str]
    null_counts: dict[str, int]
    numeric_stats: dict[str, dict[str, float]]

    def to_dict(self) -> dict[str, Any]:
        return {
            "row_count": self.row_count,
            "column_count": self.column_count,
            "column_names": list(self.column_names),
            "column_types": self.column_types,
            "null_counts": self.null_counts,
            "numeric_stats": self.numeric_stats,
        }


@dataclass(frozen=True, slots=True)
class AnalysisInput:
    """Input payload for multi-source analysis workflows."""

    input_type: str  # "document", "dataset", "image"
    content: Any
    filename: str = "input_source"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class AnalysisReport:
    """Evidence-linked report generated by AnalystEngine."""

    title: str
    query: str
    summary: str
    key_findings: tuple[str, ...]
    evidence_links: tuple[EvidenceLink, ...]
    uncertainty: UncertaintyReport
    dataset_summary: DatasetSummary | None = None
    structured_metrics: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "query": self.query,
            "summary": self.summary,
            "key_findings": list(self.key_findings),
            "evidence_links": [link.to_dict() for link in self.evidence_links],
            "uncertainty": self.uncertainty.to_dict(),
            "dataset_summary": self.dataset_summary.to_dict() if self.dataset_summary else None,
            "structured_metrics": self.structured_metrics,
        }

    def to_markdown(self) -> str:
        lines = [f"# {self.title}", ""]
        if self.query:
            lines.extend([f"**Query:** {self.query}", ""])

        lines.extend(["## Summary", self.summary, ""])

        if self.key_findings:
            lines.append("## Key Findings")
            for finding in self.key_findings:
                lines.append(f"- {finding}")
            lines.append("")

        if self.dataset_summary:
            lines.extend([
                "## Dataset Summary",
                f"- **Rows:** {self.dataset_summary.row_count}",
                f"- **Columns:** {self.dataset_summary.column_count} ({', '.join(self.dataset_summary.column_names)})",
            ])
            if self.dataset_summary.numeric_stats:
                lines.append("- **Numeric Statistics:**")
                for col, stats in self.dataset_summary.numeric_stats.items():
                    stats_str = ", ".join(f"{k}={v:.2f}" for k, v in stats.items())
                    lines.append(f"  - `{col}`: {stats_str}")
            lines.append("")

        if self.evidence_links:
            lines.append("## Evidence Links")
            for link in self.evidence_links:
                lines.append(
                    f"- [{link.id}] **{link.source_id}** ({link.location}): {link.snippet} (Confidence: {link.confidence:.2f})"
                )
            lines.append("")

        lines.extend([
            "## Uncertainty Assessment",
            f"- **Overall Uncertainty Score:** {self.uncertainty.overall_uncertainty:.2f}",
        ])
        if self.uncertainty.reasons:
            for reason in self.uncertainty.reasons:
                lines.append(f"- *Note:* {reason}")

        return "\n".join(lines)


class AnalystEngine:
    """Engine for performing structured data analysis, document analysis, image interpretation, and report generation."""

    def __init__(
        self,
        document_extractor: DocumentExtractor | None = None,
        text_chunker: TextChunker | None = None,
        diagram_evaluator: ScreenshotDiagramEvaluator | None = None,
    ) -> None:
        self.document_extractor = document_extractor or DocumentExtractor()
        self.text_chunker = text_chunker or TextChunker(chunk_size=1000, chunk_overlap=100)
        self.diagram_evaluator = diagram_evaluator or ScreenshotDiagramEvaluator()

    def analyze_dataset(
        self,
        data: list[dict[str, Any]] | str,
        filename: str = "dataset.csv",
        query: str = "",
    ) -> AnalysisReport:
        """Analyzes tabular data (CSV string or list of dict records)."""
        records, col_names = self._parse_dataset(data)

        if not records:
            return AnalysisReport(
                title=f"Dataset Analysis: {filename}",
                query=query,
                summary="Dataset is empty or could not be parsed.",
                key_findings=("No records found in dataset.",),
                evidence_links=(),
                uncertainty=UncertaintyReport(
                    overall_uncertainty=1.0,
                    reasons=("Dataset contains no readable records.",),
                    missing_data_count=0,
                    sample_size_warning=True,
                ),
            )

        row_count = len(records)
        col_count = len(col_names)

        col_types: dict[str, str] = {}
        null_counts: dict[str, int] = {col: 0 for col in col_names}
        numeric_values: dict[str, list[float]] = {col: [] for col in col_names}

        for row in records:
            for col in col_names:
                val = row.get(col)
                if val is None or val == "":
                    null_counts[col] += 1
                else:
                    try:
                        fval = float(val)
                        numeric_values[col].append(fval)
                    except (ValueError, TypeError):
                        pass

        numeric_stats: dict[str, dict[str, float]] = {}
        for col in col_names:
            nums = numeric_values[col]
            if len(nums) > 0 and len(nums) >= (row_count - null_counts[col]) * 0.8:
                col_types[col] = "numeric"
                numeric_stats[col] = {
                    "min": min(nums),
                    "max": max(nums),
                    "mean": statistics.mean(nums),
                    "median": statistics.median(nums),
                }
            else:
                col_types[col] = "text"

        ds_summary = DatasetSummary(
            row_count=row_count,
            column_count=col_count,
            column_names=tuple(col_names),
            column_types=col_types,
            null_counts=null_counts,
            numeric_stats=numeric_stats,
        )

        total_nulls = sum(null_counts.values())
        reasons: list[str] = []
        sample_warning = row_count < 5
        if sample_warning:
            reasons.append(f"Small sample size ({row_count} rows). Statistical conclusions may be unreliable.")

        if total_nulls > 0:
            reasons.append(f"Found {total_nulls} missing/null values across columns.")

        uncertainty_score = 0.0
        if sample_warning:
            uncertainty_score += 0.3
        if total_nulls > 0:
            null_ratio = total_nulls / max(1, row_count * col_count)
            uncertainty_score += min(0.5, null_ratio * 2)

        uncertainty = UncertaintyReport(
            overall_uncertainty=min(1.0, uncertainty_score),
            reasons=tuple(reasons) if reasons else ("Dataset quality appears high with no major anomalies.",),
            missing_data_count=total_nulls,
            sample_size_warning=sample_warning,
        )

        key_findings: list[str] = [
            f"Dataset contains {row_count} rows and {col_count} columns.",
        ]
        if numeric_stats:
            num_cols_str = ", ".join(f"`{c}` (mean={s['mean']:.2f})" for c, s in numeric_stats.items())
            key_findings.append(f"Numeric column summary: {num_cols_str}")

        evidence_links: list[EvidenceLink] = [
            EvidenceLink(
                id="EV-DS-001",
                source_type="dataset",
                source_id=filename,
                location=f"rows 1-{min(5, row_count)}",
                snippet=f"Sample row 1: {json.dumps(records[0], ensure_ascii=False)}",
                confidence=1.0,
            )
        ]

        summary = f"Analyzed dataset '{filename}' comprising {row_count} records across {col_count} features."
        if query:
            summary += f" Query addressed: '{query}'."

        return AnalysisReport(
            title=f"Dataset Analysis: {filename}",
            query=query,
            summary=summary,
            key_findings=tuple(key_findings),
            evidence_links=tuple(evidence_links),
            uncertainty=uncertainty,
            dataset_summary=ds_summary,
            structured_metrics={"parsed_rows": row_count, "parsed_cols": col_count},
        )

    def analyze_document(
        self,
        document: FileDocument | str,
        filename: str = "document.txt",
        query: str = "",
    ) -> AnalysisReport:
        """Analyzes unstructured or structured text documents, including large-document workflows."""
        if isinstance(document, FileDocument):
            text = self.document_extractor.extract_text(document)
            doc_name = document.filename
        else:
            text = document
            doc_name = filename

        text_length = len(text)
        if not text.strip():
            return AnalysisReport(
                title=f"Document Analysis: {doc_name}",
                query=query,
                summary="Document is empty.",
                key_findings=("Document contains no readable text content.",),
                evidence_links=(),
                uncertainty=UncertaintyReport(
                    overall_uncertainty=1.0,
                    reasons=("Empty text content.",),
                ),
            )

        # Large-document workflow check
        chunks = self.text_chunker.chunk(document_id=doc_name, text=text)
        is_large_doc = len(chunks) > 3

        evidence_links: list[EvidenceLink] = []
        key_findings: list[str] = []
        reasons: list[str] = []

        if is_large_doc:
            key_findings.append(
                f"Large document workflow engaged: Split document into {len(chunks)} chunks across {text_length} characters."
            )
            # Hierarchical chunk analysis
            for chunk in chunks[:5]:  # Extract evidence from key chunks
                evidence_links.append(
                    EvidenceLink(
                        id=f"EV-DOC-CHUNK-{chunk.chunk_index}",
                        source_type="chunk",
                        source_id=doc_name,
                        location=f"lines {chunk.start_line}-{chunk.end_line}",
                        snippet=chunk.text[:120].strip() + "...",
                        confidence=0.95,
                    )
                )
        else:
            evidence_links.append(
                EvidenceLink(
                    id="EV-DOC-001",
                    source_type="document",
                    source_id=doc_name,
                    location=f"full text ({text_length} chars)",
                    snippet=text[:150].strip() + "...",
                    confidence=1.0,
                )
            )

        lines = [line.strip() for line in text.splitlines() if line.strip()]
        key_findings.append(f"Document contains {len(lines)} non-empty lines.")

        uncertainty_score = 0.1 if not is_large_doc else 0.25
        if is_large_doc:
            reasons.append("Large document required chunking; detailed review of tail chunks may be needed.")

        summary = f"Analyzed document '{doc_name}' ({text_length} characters, {len(chunks)} chunks)."
        if query:
            summary += f" Query addressed: '{query}'."

        return AnalysisReport(
            title=f"Document Analysis: {doc_name}",
            query=query,
            summary=summary,
            key_findings=tuple(key_findings),
            evidence_links=tuple(evidence_links),
            uncertainty=UncertaintyReport(
                overall_uncertainty=uncertainty_score,
                reasons=tuple(reasons) if reasons else ("Document structure and content were verified.",),
            ),
            structured_metrics={"char_count": text_length, "chunk_count": len(chunks)},
        )

    def analyze_image(
        self,
        image_input: ImageAttachment | bytes | str,
        filename: str = "image.png",
        query: str = "",
    ) -> AnalysisReport:
        """Analyzes image content, diagrams, screenshots, or visual data."""
        if isinstance(image_input, ImageAttachment):
            attachment = image_input
        else:
            raw_bytes = image_input.encode("utf-8") if isinstance(image_input, str) else image_input
            ext = os.path.splitext(filename)[1].lstrip(".").lower()
            if ext in ("jpg", "jpeg"):
                fmt = ImageFormat.JPEG
            elif ext in ("webp",):
                fmt = ImageFormat.WEBP
            elif ext in ("gif",):
                fmt = ImageFormat.GIF
            else:
                fmt = ImageFormat.PNG

            attachment = ImageConverter.from_bytes(data=raw_bytes, format=fmt)

        # Run diagram/screenshot evaluator
        eval_result = self.diagram_evaluator.evaluate(attachment)

        fmt_str = str(eval_result.metadata.get("format", "png"))
        width = int(eval_result.metadata.get("width") or 0)
        height = int(eval_result.metadata.get("height") or 0)

        evidence_links: list[EvidenceLink] = [
            EvidenceLink(
                id="EV-IMG-001",
                source_type="image",
                source_id=filename,
                location="visual elements & viewport",
                snippet=f"Detected image format: {fmt_str}, type: {eval_result.image_type.value}",
                confidence=eval_result.confidence_score,
            )
        ]

        element_descs = [el.element_type for el in eval_result.elements]
        key_findings: list[str] = [
            f"Image classification: {eval_result.image_type.value.upper()}.",
            f"Detected visual elements: {', '.join(element_descs) if element_descs else 'General visual content'}.",
        ]
        if eval_result.detected_text:
            key_findings.append(f"Detected text elements: {', '.join(eval_result.detected_text)}")

        reasons: list[str] = []
        if eval_result.confidence_score < 0.7:
            reasons.append("Visual analysis confidence score is below optimal threshold.")

        uncertainty_score = round(1.0 - eval_result.confidence_score, 2)

        summary = f"Analyzed image '{filename}' ({eval_result.summary})."
        if query:
            summary += f" Query addressed: '{query}'."

        return AnalysisReport(
            title=f"Image Analysis: {filename}",
            query=query,
            summary=summary,
            key_findings=tuple(key_findings),
            evidence_links=tuple(evidence_links),
            uncertainty=UncertaintyReport(
                overall_uncertainty=uncertainty_score,
                reasons=tuple(reasons) if reasons else ("Image quality and structure verified.",),
            ),
            structured_metrics={
                "image_type": eval_result.image_type.value,
                "width": width,
                "height": height,
                "confidence_score": eval_result.confidence_score,
            },
        )

    def analyze_multi_source(
        self,
        inputs: list[AnalysisInput],
        query: str = "",
    ) -> AnalysisReport:
        """Synthesizes analysis across multiple structured sources (documents, datasets, images)."""
        reports: list[AnalysisReport] = []
        all_evidence: list[EvidenceLink] = []
        all_findings: list[str] = []
        all_reasons: list[str] = []
        uncertainty_scores: list[float] = []

        for item in inputs:
            if item.input_type == "dataset":
                rep = self.analyze_dataset(item.content, filename=item.filename, query=query)
            elif item.input_type == "document":
                rep = self.analyze_document(item.content, filename=item.filename, query=query)
            elif item.input_type == "image":
                rep = self.analyze_image(item.content, filename=item.filename, query=query)
            else:
                continue

            reports.append(rep)
            all_evidence.extend(rep.evidence_links)
            all_findings.extend(rep.key_findings)
            all_reasons.extend(rep.uncertainty.reasons)
            uncertainty_scores.append(rep.uncertainty.overall_uncertainty)

        avg_uncertainty = (
            statistics.mean(uncertainty_scores) if uncertainty_scores else 0.5
        )

        summary = f"Synthesized analysis across {len(inputs)} multi-source inputs."
        if query:
            summary += f" Query addressed: '{query}'."

        return AnalysisReport(
            title="Multi-Source Synthesized Analysis Report",
            query=query,
            summary=summary,
            key_findings=tuple(all_findings),
            evidence_links=tuple(all_evidence),
            uncertainty=UncertaintyReport(
                overall_uncertainty=round(avg_uncertainty, 3),
                reasons=tuple(all_reasons),
            ),
            structured_metrics={"source_count": len(inputs)},
        )

    def _parse_dataset(
        self, data: list[dict[str, Any]] | str
    ) -> tuple[list[dict[str, Any]], list[str]]:
        if isinstance(data, list):
            if not data:
                return [], []
            col_names = list(data[0].keys())
            return data, col_names

        cleaned = data.strip()
        if not cleaned:
            return [], []

        # Try parsing JSON first
        if cleaned.startswith("[") or cleaned.startswith("{"):
            try:
                parsed = json.loads(cleaned)
                if isinstance(parsed, list) and parsed and isinstance(parsed[0], dict):
                    return parsed, list(parsed[0].keys())
                if isinstance(parsed, dict):
                    return [parsed], list(parsed.keys())
            except json.JSONDecodeError:
                pass

        # Try CSV parsing
        f = io.StringIO(cleaned)
        reader = csv.DictReader(f)
        try:
            records = [dict(row) for row in reader]
            col_names = reader.fieldnames or []
            return records, list(col_names)
        except Exception:
            return [], []
